#-------------------------------
# General Site Settings
title: Choyeon An's Portfolio
logo: logo.svg # You can add own logo.
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Alex Rodriguez
  image: 01.jpg
  say-hello: Hello, I’m <strong>Choyeon An</strong>
  bio: I’m an ambitious and focused data scientist. I’ve worked on big data system projects for 4 years mostly in the banking industry. Up till now, I have concentrated on utilising Python and SQL to enhance IT process systems through data science methods. 
  My skillset includes <strong>Data Analysis</strong>, <strong>Machine Learning</strong>, <strong>Deep Learning</strong>, and NLP. 
  I’m interested in learning more about NLP techniques these days. Loves <a href="#">music</a> & riding his bicycle.


#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
